### ISSUE TITLE
GOTOs don't handle arithmetic

### ISSUE THREAD

**Issue by jakerman999** [Kyromyr/Kyromyr.github.io#4]
In cases where the target line isn't known ahead of time (E.G. target line is a multiple of factory item tier) it is useful to perform math operations inside a GOTO or a GOTOIF.  The editor can import such scripts with no trouble, but cannot generate an import string.

Please see this small script for an example
`AAAAAAAAAAAAAQAAAAxnZW5lcmljLmdvdG8OYXJpdGhtZXRpYy5pbnQOZ2xvYmFsLmludC5nZXQIY29uc3RhbnQECnNvbWVfdmFsdWUIY29uc3RhbnQEASoIY29uc3RhbnQCAgAAAA==`

**Comment by Kyromyr** [comment]
Fixed. 66cba571f4b07bbb49de016ab84bfcd295b03f23
